// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emtqiplniuzeknejwesf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdHFpcGxuaXV6ZWtuZWp3ZXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MjM4NjMsImV4cCI6MjA2NjQ5OTg2M30.tbMgOgI4pjNqXKqjA58OUXH4-7BndfwjCSg9pYsI7xA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});